### ISSUE TITLE
Microsoft Edge compatibility issue. Errors in commons

### ISSUE THREAD

**Issue by reallymello** [Chronoblog/gatsby-theme-chronoblog#24]
On Edge 44 on Windows the console has "security" errors so the site functionality doesn't load. You get a base UI, but none of the blog images size correctly and navigation doesn't work. Chrome and Firefox don't appear to be affected.

[object Error]: {description: "A security problem occurred. ", message: "A security problem occurred. ", number: -2146697202, stack: "Error: A security problem occurred. at l (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:275197) at s (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:6426) at f (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:6910) at si (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:354464) at Mc (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:399508) at ml (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:385219) at dl (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:385147) at ol (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:382498) at el (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:379229) at Fl (https://chronoblog.now.sh/commons-831fa7fe1a4518f96da1.js:1:407048)"}

![brokenPage](https://user-images.githubusercontent.com/18431256/72345595-287b6a00-36a2-11ea-8a82-6d271c1df68e.png)

**Comment by Ganevru** [comment]
Yes, I have the same thing on edge. I have absolutely no idea what it is.

I also tried edge beta - everything is fine there.

In general, I am sure that when the edge is updated (when it switches to chromium) this error will disappear.
